# Generated by Django 5.2.17 on 2026-08-27 16:13

import django.db.models.deletion
import interviews.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('position', models.CharField(max_length=160)),
                ('candidate_name', models.CharField(max_length=160)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('job_description', models.TextField()),
                ('rubric', models.TextField(blank=True)),
                ('resume_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('scheduled', 'Planlandı'), ('live', 'Canlı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal')], db_index=True, default='scheduled', max_length=16)),
                ('recording_enabled', models.BooleanField(default=False)),
                ('research_mode', models.BooleanField(default=False)),
                ('retention_days', models.PositiveSmallIntegerField(default=30)),
                ('consent_version', models.CharField(default='v1.0', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=160)),
                ('version', models.CharField(max_length=32)),
                ('accepted', models.BooleanField(default=True)),
                ('camera_optional_acknowledged', models.BooleanField(default=False)),
                ('recording_acknowledged', models.BooleanField(default=False)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='interviews.interview')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='interviews.interview')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('clarify', 'Netleştirme'), ('depth', 'Teknik derinlik'), ('evidence', 'Kanıt'), ('tradeoff', 'Takas/tercih'), ('reflection', 'Değerlendirme'), ('competency_gap', 'Yeterlik boşluğu')], max_length=24)),
                ('priority', models.PositiveSmallIntegerField(default=2)),
                ('rationale', models.CharField(max_length=500)),
                ('evidence_span_ids', models.JSONField(default=list)),
                ('prohibited_topic', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('suggested', 'Önerildi'), ('asked', 'Soruldu'), ('dismissed', 'Reddedildi')], default='suggested', max_length=16)),
                ('provider', models.CharField(default='rules', max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_questions', to='interviews.interview')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('span_id', models.CharField(default=interviews.models.new_span_id, max_length=32, unique=True)),
                ('speaker', models.CharField(choices=[('candidate', 'Aday'), ('interviewer', 'Mülakatçı')], max_length=16)),
                ('text', models.TextField()),
                ('is_final', models.BooleanField(default=True)),
                ('started_ms', models.PositiveBigIntegerField(default=0)),
                ('ended_ms', models.PositiveBigIntegerField(default=0)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='whisper', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_segments', to='interviews.interview')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['interview', 'created_at'], name='interviews__intervi_c9a4c3_idx')],
            },
        ),
    ]
